/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.Map;
import javax.swing.table.DefaultTableModel;
import models.DBManager;
import models.Order;
import models.OrderLine;
import models.ZooKeeper;

/**
 *
 * @author jahood
 */
public class Basket extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Basket.class.getName());

    private Order currentOrder;
    private ZooKeeper loggedInZooKeeper;
    
    /**
     * Creates new form Basket
     */
    //public Basket(ZooKeeper zk,Order currentOrder) {// fix imports
    public Basket(ZooKeeper zk,Order o) {// fix imports
        
        loggedInZooKeeper = zk;
        currentOrder =o;
        
        initComponents();
        
        DefaultTableModel animalBasketModel = (DefaultTableModel)tblAnimalBasket.getModel();
        
        for(Map.Entry<Integer, OrderLine> olMapEntry : currentOrder.getOrderLines().entrySet())//global variable
        {
            OrderLine actualOrderLine = olMapEntry.getValue();
            
            animalBasketModel.addRow(new Object[] {
                actualOrderLine.getAnimalBought().getAnimalId(),
                actualOrderLine.getAnimalBought().getType() + "-" + actualOrderLine.getAnimalBought().getName(),
                "£" + actualOrderLine.getAnimalBought().getCost()
            });
        }
        
        tblAnimalBasket.setModel(animalBasketModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimalBasket = new javax.swing.JTable();
        btnOrderAnimals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAnimalBasket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal ID", "Animal", "Cost"
            }
        ));
        jScrollPane1.setViewportView(tblAnimalBasket);

        btnOrderAnimals.setText("Order Animals");
        btnOrderAnimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderAnimalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnOrderAnimals))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrderAnimals)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // button Order Animals clicked
    // Saves the order to the database and
    // transitioning the user to an order confirmation screen.
    private void btnOrderAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderAnimalsActionPerformed
        // TODO add your handling code here:
        // make a call to.. and pass to ...
        DBManager db = new DBManager();
        // create getter in Person class
        db.writeOrder(currentOrder, loggedInZooKeeper.getEmail());
        
        // show the OrderConfirmation frame
        OrderConfirmation oc = new OrderConfirmation(loggedInZooKeeper);
        oc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOrderAnimalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   //     java.awt.EventQueue.invokeLater(() -> new Basket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderAnimals;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnimalBasket;
    // End of variables declaration//GEN-END:variables
}
